spring:
  application:
    name: fun-school-workshop
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  info:
    git:
      mode: simple
    env:
      enabled: true
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true
  jolokia:
    enabled: true
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    username: worksheets
    password: sekritPazzword
    url: jdbc:h2:mem:worksheets;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      idle-timeout: 10000
      connection-test-query: select 1
  h2:
    console:
      enabled: true
      path: /h2ws
      settings:
        web-allow-others: true
server:
  port: 12345
